---
- name: apply common configuration all nodes
  hosts: all
  remote_user: user

  roles:
    - common

- name: configuration and deploy the nfs server(storage)
  hosts: storage
  remote_user: user
  vars_files:
    - global_vars/storage/storage.yaml 

  roles:
    - storage

- name: deploy MySQL and configure the databases
  hosts: db
  remote_user: user
  var_files:
    - global_vars/db/db.yaml
    - global_vars/db/db_user_password.yaml
    - global_vars/db/mysql_root_password.yaml

  roles:
    - db
